# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 504fe12d87e07ab2ecbf326358c0dfb7dd7f9334e2437216fd04a8866fa3d63c7c60a83901f548dc347e7667d9c0a24dd889f4a3bdf22511e1a578cb6bfdf353

test:
  secret_key_base: 2c3826b0a2c9abacecd66d46fadc6552c2984366e8feb98ded58752ea54a3e754acf42871b34939044436fb3b56870cbdd86cdbb14bc82e7af936924fb331623

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
