# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9df1695606afb937a6785ca497e2eb5214c19a3d3461858507e7128b16deefd9759a88c29aee99f4333fd4b295470689caaa53e611179600aa0f938bc51e5340

test:
  secret_key_base: b166021d49e74fcb6e0d2bd856b5c1540ef4f00147aa3069bc2ccdc21d30fa2bbe4a77f9790dace6229565c783d9cdbcdd294050eef7ef36012a2ad4a74dd7c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
